# Generated by Django 5.1.15 on 2026-06-05 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('OPEN_REVIEW', 'Open review'), ('REQUEST_EDIT', 'Request edit'), ('EDIT_VALUE', 'Edit value'), ('DECLINE', 'Decline'), ('QC_APPROVE', 'QC approve'), ('REOPEN', 'Reopen'), ('COMMENT', 'Comment'), ('SUPERSEDE', 'Supersede')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('field_key', models.CharField(blank=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='submissions.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('INGESTED', 'Ingested'), ('FLAGGED', 'Flagged'), ('IN_REVIEW', 'In review'), ('EDIT_REQUESTED', 'Edit requested'), ('EDITED', 'Edited'), ('DECLINED', 'Declined'), ('QC_PENDING', 'QC pending'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='INGESTED', max_length=20)),
                ('qc_signed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('qc_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_signed_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='submissions.submission')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['state'], name='review_revi_state_9ec410_idx')],
            },
        ),
    ]
