# Generated by Django 5.1.15 on 2026-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewactionlog',
            name='action',
            field=models.CharField(choices=[('OPEN_REVIEW', 'Open review'), ('REQUEST_EDIT', 'Request edit'), ('EDIT_VALUE', 'Edit value'), ('DECLINE', 'Decline'), ('QC_APPROVE', 'QC approve'), ('REOPEN', 'Reopen'), ('COMMENT', 'Comment'), ('SUPERSEDE', 'Supersede'), ('SYSTEM_FLAG', 'System flag')], max_length=20),
        ),
    ]
