# Generated by Django 5.1.15 on 2026-06-26 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewactionlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='endorsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='endorsed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewactionlog',
            name='action',
            field=models.CharField(choices=[('OPEN_REVIEW', 'Open review'), ('REQUEST_EDIT', 'Request edit'), ('EDIT_VALUE', 'Edit value'), ('DECLINE', 'Decline'), ('ENDORSE', 'Endorse (level 1)'), ('QC_APPROVE', 'Validate (final)'), ('REOPEN', 'Reopen'), ('COMMENT', 'Comment'), ('SUPERSEDE', 'Supersede'), ('SYSTEM_FLAG', 'System flag'), ('ASSIGN', 'Assign')], max_length=20),
        ),
    ]
