# Generated by Django 5.1.15 on 2026-07-01 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_endorsed_at_review_endorsed_by_and_more'),
        ('projects', '0008_usecase_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='projects.usecase')),
            ],
            options={
                'ordering': ['order', 'label'],
                'unique_together': {('use_case', 'code')},
            },
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='review.rejectionreason'),
        ),
    ]
