# Generated by Django 5.1.15 on 2026-06-26 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_country_region_usecase_country_country_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('database_alias', models.CharField(default='default', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.SlugField(max_length=32),
        ),
        migrations.AddField(
            model_name='region',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='projects.organization'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='projects.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('organization', 'code')},
        ),
    ]
