# Generated by Django 5.1.15 on 2026-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='publish_status',
            field=models.CharField(choices=[('EXTERNAL', 'External (onboarded)'), ('PUBLISHED', 'Published from XLSForm'), ('FAILED', 'Publish failed')], default='EXTERNAL', max_length=12),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='server_form_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='xlsform',
            field=models.FileField(blank=True, null=True, upload_to='xlsforms/'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='ona_form_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('server_form_id__gt', '')), fields=('use_case', 'server_form_id'), name='uniq_form_server_id'),
        ),
    ]
