# Generated by Django 5.1.15 on 2026-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_usecase_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='field_schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
