# Generated by Django 5.1.15 on 2026-07-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_usecase_to_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['project']},
        ),
        migrations.AlterModelOptions(
            name='eventscheduleitem',
            options={'ordering': ['project', 'sequence']},
        ),
        migrations.AlterModelOptions(
            name='formdefinition',
            options={'ordering': ['project', 'role', 'ona_form_id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.organization'),
        ),
    ]
