# Generated by Django 5.1.15 on 2026-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_datasource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_access_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
