# Generated by Django 5.1.15 on 2026-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_backfill_owner_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='database_url',
            field=models.CharField(blank=True, help_text='Or a full DB connection URL this institution grants access to (e.g. postgres://user:pass@host:5432/db). Overrides the alias.', max_length=500),
        ),
        migrations.AlterField(
            model_name='organization',
            name='database_alias',
            field=models.CharField(default='default', help_text='Django DATABASES alias (default = shared platform DB).', max_length=64),
        ),
    ]
