# Generated by Django 5.1.15 on 2026-07-04 12:21

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_organization_database_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='database_url',
            field=apps.common.fields.EncryptedCharField(blank=True, help_text='Or a full DB connection URL this institution grants access to (e.g. postgres://user:pass@host:5432/db). Overrides the alias. Encrypted at rest.', max_length=1200),
        ),
    ]
