# Generated by Django 5.1.15 on 2026-07-04 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_organization_database_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('form_id', models.SlugField(blank=True, max_length=100)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Built by hand'), ('AI', 'Drafted from a protocol')], default='MANUAL', max_length=8)),
                ('role', models.CharField(default='VALIDATION', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('missing_terms', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_form_drafts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_drafts', to='projects.project')),
                ('published_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.formdefinition')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
