# Generated by Django 5.1.15 on 2026-07-22 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_formdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('SAMPLING_FRAME', 'Sampling frame (expected records)'), ('LAB_RESULTS', 'Laboratory results'), ('LOOKUP', 'Lookup / valid values')], default='LOOKUP', max_length=20)),
                ('key_field', models.CharField(max_length=64)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_datasets', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=160)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='projects.referencedataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'key'], name='projects_re_dataset_f9d6c4_idx')],
            },
        ),
    ]
