# Generated by Django 5.1.15 on 2026-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_referencedataset_referencerow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hhid_patterns',
            new_name='id_patterns',
        ),
        # Rename (not drop+add) so existing per-project labels — "Plots", "Farmers",
        # "Household" — are preserved; only the default for NEW projects changes.
        migrations.RenameField(
            model_name='project',
            old_name='household_label',
            new_name='unit_label',
        ),
        migrations.AlterField(
            model_name='project',
            name='unit_label',
            field=models.CharField(default='Collection unit', max_length=64),
        ),
    ]
