# Generated by Django 5.1.15 on 2026-06-05 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('rule_type', models.CharField(choices=[('REGEX_ID', 'Regex ID check'), ('EVENT_SEQUENCE', 'Event sequence check'), ('DATE_WINDOW', 'Date-window / schedule check'), ('NUMERIC_RANGE', 'Numeric range / outlier check'), ('REQUIRED_FIELD', 'Required field present'), ('CROSS_FIELD', 'Cross-field check'), ('PLUGIN', 'Plugin-provided check')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=10)),
                ('auto_flag_state', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.usecase')),
            ],
            options={
                'ordering': ['use_case', 'code'],
                'unique_together': {('use_case', 'code')},
            },
        ),
    ]
