# Generated by Django 5.1.15 on 2026-06-05 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        ('validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('field_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('WAIVED', 'Waived')], default='OPEN', max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='validation.validationrule')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='submissions.submission')),
            ],
            options={
                'ordering': ['submission', 'rule'],
                'indexes': [models.Index(fields=['status', 'severity'], name='validation__status_104ffa_idx')],
                'unique_together': {('submission', 'rule', 'field_key')},
            },
        ),
    ]
