# Generated by Django 5.1.15 on 2026-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_validationflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(choices=[('REGEX_ID', 'Regex ID check'), ('EVENT_SEQUENCE', 'Event sequence check'), ('DATE_WINDOW', 'Date-window / schedule check'), ('NUMERIC_RANGE', 'Numeric range / outlier check'), ('REQUIRED_FIELD', 'Required field present'), ('CROSS_FIELD', 'Cross-field check'), ('GEO_DISTANCE', 'GPS distance from assigned plot'), ('PLUGIN', 'Plugin-provided check')], max_length=20),
        ),
    ]
