# Generated by Django 5.1.15 on 2026-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_alter_validationrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(choices=[('REGEX_ID', 'Regex ID check'), ('EVENT_SEQUENCE', 'Event sequence check'), ('DATE_WINDOW', 'Date-window / schedule check'), ('NUMERIC_RANGE', 'Numeric range / outlier check'), ('REQUIRED_FIELD', 'Required field present'), ('CROSS_FIELD', 'Cross-field check'), ('GEO_DISTANCE', 'GPS distance from assigned plot'), ('GEO_CONTAINMENT', 'GPS inside the elected plot boundary'), ('NUMERIC_OUTLIER', 'Numeric statistical outlier'), ('GEO_DUPLICATE', 'Shared GPS across households (integrity)'), ('SUBMISSION_SPEED', 'Implausible submission pace (integrity)'), ('PHOTO_REUSE', 'Reused photo across households (integrity)'), ('PLUGIN', 'Plugin-provided check')], max_length=20),
        ),
    ]
