# Generated by Django 5.1.15 on 2026-07-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0008_alter_validationrule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(choices=[('REGEX_ID', 'Regex ID check'), ('EVENT_SEQUENCE', 'Event sequence check'), ('DATE_WINDOW', 'Date-window / schedule check'), ('NUMERIC_RANGE', 'Numeric range / outlier check'), ('REQUIRED_FIELD', 'Required field present'), ('CROSS_FIELD', 'Cross-column check (sum/relation)'), ('CONDITIONAL_REQ', 'Conditionally required field'), ('UNIQUE_FIELD', 'Unique field (duplicate detection)'), ('GEO_DISTANCE', 'GPS distance from assigned plot'), ('GEO_CONTAINMENT', 'GPS inside the elected plot boundary'), ('NUMERIC_OUTLIER', 'Numeric statistical outlier (z-score / IQR)'), ('GEO_DUPLICATE', 'Shared GPS across households (integrity)'), ('SUBMISSION_SPEED', 'Implausible submission pace (integrity)'), ('PHOTO_REUSE', 'Reused photo across households (integrity)'), ('PLUGIN', 'Plugin-provided check')], max_length=20),
        ),
    ]
