# Generated by Django 5.1.15 on 2026-07-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_formdraft'),
        ('validation', '0009_alter_validationrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrule',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.formdefinition'),
        ),
    ]
