# Generated by Django 5.1.15 on 2026-06-27 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0004_submission_collection_unit'),
        ('projects', '0008_usecase_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(default='daily_submissions', max_length=64)),
                ('comparator', models.CharField(choices=[('LT', 'is below'), ('LTE', 'is at or below'), ('GT', 'is above'), ('GTE', 'is at or above')], default='LT', max_length=4)),
                ('threshold', models.FloatField(default=0)),
                ('consecutive_days', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=8)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notify_emails', models.JSONField(blank=True, default=list)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='projects.usecase')),
            ],
            options={
                'ordering': ['use_case', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=8)),
                ('message', models.TextField(blank=True)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='projects.usecase')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kpi.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnumeratorKpiDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('enumerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_daily', to='submissions.enumerator')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerator_kpi_daily', to='projects.usecase')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('enumerator', 'use_case', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FormKpiDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_daily', to='projects.formdefinition')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('form', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectKpiDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('active_enumerators', models.PositiveIntegerField(default=0)),
                ('flags_opened', models.PositiveIntegerField(default=0)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_daily', to='projects.usecase')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['use_case', 'date'], name='kpi_project_use_cas_309b03_idx')],
                'unique_together': {('use_case', 'date')},
            },
        ),
    ]
