# Generated by Django 5.1.15 on 2026-07-04 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('data_type', models.CharField(blank=True, max_length=16)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('multiple_allowed', models.BooleanField(default=False)),
                ('value_list', models.CharField(blank=True, max_length=64)),
                ('valid_min', models.FloatField(blank=True, null=True)),
                ('valid_max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('obo', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_preferred', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['list_name', 'name'],
                'indexes': [models.Index(fields=['list_name'], name='vocabulary__list_na_00b15d_idx')],
                'constraints': [models.UniqueConstraint(fields=('list_name', 'name'), name='uniq_vocab_value_per_list')],
            },
        ),
    ]
