# Generated by Django 5.1.15 on 2026-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasemembership',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('REGIONAL_COORDINATOR', 'Regional Coordinator'), ('COUNTRY_COORDINATOR', 'Country Coordinator'), ('TRIAL_COORDINATOR', 'Trial / Survey Coordinator'), ('SURVEY_DOMAIN_EXPERT', 'Survey Domain Expert'), ('QUALITY_CHECK', 'Quality Check / Agronomist'), ('ENUMERATOR', 'Enumerator'), ('VIEWER', 'Viewer')], max_length=32),
        ),
    ]
