# Generated by Django 5.1.15 on 2026-06-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_usecasemembership_role'),
        ('projects', '0004_country_region_usecase_country_country_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usecasemembership',
            options={'ordering': ['use_case', 'country', 'region', 'role']},
        ),
        migrations.AlterUniqueTogether(
            name='usecasemembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usecasemembership',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.country'),
        ),
        migrations.AddField(
            model_name='usecasemembership',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.region'),
        ),
        migrations.AlterField(
            model_name='usecasemembership',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.usecase'),
        ),
        migrations.AddConstraint(
            model_name='usecasemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('country__isnull', True), ('region__isnull', True), ('use_case__isnull', False)), models.Q(('country__isnull', False), ('region__isnull', True), ('use_case__isnull', True)), models.Q(('country__isnull', True), ('region__isnull', False), ('use_case__isnull', True)), _connector='OR'), name='membership_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='usecasemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('use_case__isnull', False)), fields=('user', 'use_case', 'role'), name='uniq_membership_use_case'),
        ),
        migrations.AddConstraint(
            model_name='usecasemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('country__isnull', False)), fields=('user', 'country', 'role'), name='uniq_membership_country'),
        ),
        migrations.AddConstraint(
            model_name='usecasemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False)), fields=('user', 'region', 'role'), name='uniq_membership_region'),
        ),
    ]
