# Generated by Django 5.1.15 on 2026-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_usecasemembership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasemembership',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('REGIONAL_COORDINATOR', 'Regional Coordinator'), ('COUNTRY_COORDINATOR', 'Country Coordinator'), ('TRIAL_COORDINATOR', 'Trial / Survey Coordinator'), ('ENUMERATOR', 'Enumerator'), ('VIEWER', 'Viewer')], max_length=32),
        ),
    ]
