# Generated by Django 5.1.15 on 2026-06-27 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usecases', '0008_usecase_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_units', to='usecases.usecase')),
            ],
            options={
                'ordering': ['use_case', 'code'],
                'unique_together': {('use_case', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='usecases.formdefinition')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='usecases.usecase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enumerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_assignments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fieldwork.job')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fieldwork.collectionunit')),
            ],
            options={
                'ordering': ['job', 'unit'],
                'unique_together': {('job', 'unit')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='fieldwork.UnitAssignment', to='fieldwork.collectionunit'),
        ),
    ]
