# Generated by Django 5.1.15 on 2026-07-02 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0002_job_closed_at_job_closed_by_job_closure_note'),
        ('projects', '0009_formdefinition_field_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_key', models.CharField(max_length=64)),
                ('candidate_ref', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('BACKUP', 'Backup')], default='PRIMARY', max_length=8)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('accessibility', models.CharField(blank=True, max_length=32)),
                ('cropping_region', models.CharField(blank=True, max_length=128)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('centroid_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('centroid_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ELECTED', 'Elected'), ('NOT_SELECTED', 'Not selected')], default='PROPOSED', max_length=12)),
                ('elected_at', models.DateTimeField(blank=True, null=True)),
                ('election_note', models.CharField(blank=True, max_length=255)),
                ('collection_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidate', to='fieldwork.collectionunit')),
                ('elected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elected_plots', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_plots', to='projects.usecase')),
            ],
            options={
                'ordering': ['use_case', 'trial_key', 'rank', 'candidate_ref'],
                'indexes': [models.Index(fields=['use_case', 'trial_key'], name='fieldwork_c_use_cas_613427_idx')],
                'unique_together': {('use_case', 'trial_key', 'candidate_ref')},
            },
        ),
    ]
