# Generated by Django 5.1.15 on 2026-07-02 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0003_candidateplot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionunit',
            name='anchor_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionunit',
            name='anchor_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionunit',
            name='anchor_captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_anchors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionunit',
            name='boundary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
