# Generated by Django 5.1.15 on 2026-07-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0004_collectionunit_anchor_captured_and_more'),
        ('submissions', '0009_submission_media_hashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionunit',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collectionunit',
            name='enumerator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_units', to='submissions.enumerator'),
        ),
        migrations.AddField(
            model_name='collectionunit',
            name='site_selection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
