# Generated by Django 5.1.15 on 2026-07-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0007_rename_use_case_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateplot',
            options={'ordering': ['project', 'trial_key', 'rank', 'candidate_ref']},
        ),
        migrations.AlterModelOptions(
            name='collectionunit',
            options={'ordering': ['project', 'code']},
        ),
    ]
