# Generated by Django 5.1.15 on 2026-09-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0008_alter_candidateplot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_to',
        ),
    ]
