# Generated by Django 5.1.15 on 2026-06-26 07:47

import uuid

from django.db import migrations, models


def populate_user_ids(apps, schema_editor):
    """Stamp every existing user with a unique platform UserID before the
    unique constraint is applied — empty strings would collide otherwise."""
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(user_id="").iterator():
        user.user_id = "U-" + uuid.uuid4().hex[:8].upper()
        user.save(update_fields=["user_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.RunPython(populate_user_ids, noop),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
