# Generated by Django 5.1.15 on 2026-06-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('second_name', models.CharField(blank=True, max_length=128)),
                ('family_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other / prefer not to say')], max_length=8)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('no_school', 'No school'), ('primary', 'Primary'), ('secondary', 'Secondary (high school or academy)'), ('post_secondary', 'Post-secondary (college / university)'), ('adult_education', 'Adult education / literacy / religious school'), ('no_answer', 'No answer / prefer not to say')], max_length=20)),
                ('phone_alt', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('enumerator_card_id', models.CharField(blank=True, max_length=32)),
                ('consent_personal_info', models.BooleanField(default=False)),
                ('consent_followup', models.BooleanField(default=False)),
                ('consent_photos', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
