# Generated by Django 5.1.15 on 2026-06-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enumerator_card_id',
        ),
    ]
