# Generated by Django 5.1.15 on 2026-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_enumerator_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
