# Generated by Django 5.1.15 on 2026-07-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='second_name',
        ),
    ]
