# Generated by Django 5.1.15 on 2026-06-05 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usecases', '0002_usecase_test_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumerator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enid', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_test', models.BooleanField(default=False)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enumerators', to='usecases.usecase')),
            ],
            options={
                'ordering': ['enid'],
                'unique_together': {('use_case', 'enid')},
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hhid', models.CharField(max_length=64)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('alt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('site_selection_date', models.DateField(blank=True, null=True)),
                ('enumerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='submissions.enumerator')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='usecases.usecase')),
            ],
            options={
                'ordering': ['hhid'],
                'unique_together': {('use_case', 'hhid')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ona_submission_id', models.BigIntegerField(blank=True, null=True)),
                ('ona_uuid', models.CharField(max_length=128)),
                ('ona_submission_time', models.DateTimeField(blank=True, null=True)),
                ('ona_edited', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('event_key', models.CharField(blank=True, max_length=32)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usecases.crop')),
                ('enumerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='submissions.enumerator')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='usecases.formdefinition')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='submissions.household')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usecases.stage')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usecases.trial')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='usecases.usecase')),
            ],
            options={
                'ordering': ['-event_date', '-ona_submission_time'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(max_length=64)),
                ('raw_value', models.JSONField(blank=True, null=True)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('INGEST', 'Ingested from ONA'), ('REVIEWER_EDIT', 'Edited by reviewer'), ('PLUGIN', 'Produced by plugin')], default='INGEST', max_length=16)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='submissions.submission')),
            ],
            options={
                'ordering': ['submission', 'field_key'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['use_case', 'event_key'], name='submissions_use_cas_4bdd98_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['use_case', 'enumerator'], name='submissions_use_cas_0e12c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('use_case', 'ona_uuid'), name='uq_submission_use_case_uuid'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionvalue',
            unique_together={('submission', 'field_key')},
        ),
    ]
