# Generated by Django 5.1.15 on 2026-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='writeback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='writeback_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='writeback_status',
            field=models.CharField(choices=[('NONE', 'Not attempted'), ('PENDING', 'Pending'), ('SENT', 'Sent to source'), ('FAILED', 'Failed'), ('UNSUPPORTED', 'Unsupported by source')], default='NONE', max_length=12),
        ),
    ]
