# Generated by Django 5.1.15 on 2026-06-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0001_initial'),
        ('submissions', '0003_enumerator_user_submission_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='collection_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='fieldwork.collectionunit'),
        ),
    ]
