# Generated by Django 5.1.15 on 2026-06-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_collection_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
