# Generated by Django 5.1.15 on 2026-06-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_backfill_submission_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionvalue',
            name='field_key',
            field=models.CharField(max_length=200),
        ),
    ]
