# Generated by Django 5.1.15 on 2026-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submissionvalue_field_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='media_hashes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
