# Generated by Django 5.1.15 on 2026-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submission_media_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='media_hashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
