# Generated by Django 5.1.15 on 2026-07-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_submission_media_hashed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='household',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
    ]
