# Generated by Django 5.1.15 on 2026-07-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_remove_submission_household_delete_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='stage',
        ),
    ]
