# Generated by Django 5.1.15 on 2026-07-04 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_organization_database_url'),
        ('submissions', '0012_rename_use_case_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(max_length=32)),
                ('remote_id', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('LINKED', 'Linked (already existed)'), ('FAILED', 'Failed'), ('UNSUPPORTED', 'Backend has no provisioning')], default='PENDING', max_length=12)),
                ('message', models.TextField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector_accounts', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'project'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'project'), name='uniq_collector_account_user_project'), models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('user',), name='uniq_collector_account_user_serverwide')],
            },
        ),
    ]
