# Generated by Django 5.1.15 on 2026-07-22 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_collectoraccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissionvalue',
            index=models.Index(fields=['field_key'], name='submissions_field_k_dcc4ca_idx'),
        ),
    ]
