# Generated by Django 5.1.15 on 2026-06-05 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('enid_patterns', models.JSONField(blank=True, default=list)),
                ('hhid_patterns', models.JSONField(blank=True, default=list)),
                ('plugin_path', models.CharField(blank=True, max_length=255)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('household_label', models.CharField(default='Household', max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ona_form_id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('ENUM_REG', 'Enumerator registration'), ('HH_REG', 'Household registration'), ('VALIDATION', 'Validation data'), ('NOT', 'Nutrient-omission trial'), ('INTERCROP', 'Intercropping'), ('EXTRA', 'Extra')], max_length=16)),
                ('season', models.CharField(blank=True, max_length=16)),
                ('system_vars_drop', models.JSONField(blank=True, default=list)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usecases.crop')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='usecases.usecase')),
            ],
            options={
                'ordering': ['use_case', 'role', 'ona_form_id'],
                'unique_together': {('use_case', 'ona_form_id')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_field', models.CharField(max_length=64)),
                ('source_paths', models.JSONField(blank=True, default=list)),
                ('transform', models.CharField(choices=[('DIRECT', 'Direct copy'), ('COALESCE', 'First non-null of sources'), ('SPLIT_GEOPOINT', "Split 'lat lon alt err' geopoint"), ('REGEX_SUB', 'Regex substitution'), ('DATE_PARSE', 'Parse to date'), ('CONST', 'Constant value'), ('LOOKUP', 'Resolve via crop/alias lookup')], default='DIRECT', max_length=20)),
                ('transform_args', models.JSONField(blank=True, default=dict)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='usecases.formdefinition')),
            ],
            options={
                'ordering': ['form', 'order', 'target_field'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='usecases.usecase'),
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='usecases.usecase')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('use_case', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='usecases.usecase')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('use_case', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=32)),
                ('sequence', models.IntegerField()),
                ('anchor', models.CharField(choices=[('SITE_SELECTION', 'Site selection date'), ('EVENT1', 'Event 1 date'), ('PREV_EVENT', 'Previous event date')], default='EVENT1', max_length=20)),
                ('offset_days', models.IntegerField(default=0)),
                ('crop_overrides', models.JSONField(blank=True, default=dict)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='usecases.usecase')),
            ],
            options={
                'ordering': ['use_case', 'sequence'],
                'unique_together': {('use_case', 'event_key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('use_case', 'name')},
        ),
    ]
