# Generated by Django 5.1.15 on 2026-06-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='test_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
