# Generated by Django 5.1.15 on 2026-06-25 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0002_usecase_test_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(default='ONA', max_length=32)),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(blank=True, max_length=512)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_source', to='usecases.usecase')),
            ],
            options={
                'ordering': ['use_case'],
            },
        ),
    ]
