# Generated by Django 5.1.15 on 2026-06-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0007_formdefinition_publish_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='unit_type',
            field=models.CharField(choices=[('PLOT', 'Plot'), ('FARMER_HOUSEHOLD', 'Farmer / Household')], default='FARMER_HOUSEHOLD', max_length=20),
        ),
    ]
