# Generated by Django 5.1.15 on 2026-07-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_remove_submission_stage'),
        ('usecases', '0009_formdefinition_field_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
