# Generated by Django 5.1.15 on 2026-07-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0010_delete_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usecase',
            options={'ordering': ['code'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
