# Generated by Django 5.1.15 on 2026-07-22 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0022_referencedataset_referencerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('OK', 'OK'), ('ERROR', 'Error')], default='RUNNING', max_length=10)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='ingestion_s_project_9d894b_idx')],
            },
        ),
    ]
