# Generated by Django 5.1.15 on 2026-07-23 15:44

import apps.common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('projects', '0022_referencedataset_referencerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('WEBHOOK', 'Webhook (HTTP POST JSON)')], default='WEBHOOK', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('secret', apps.common.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('only_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cursor', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('OK', 'OK'), ('ERROR', 'Error')], max_length=10)),
                ('last_message', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
    ]
