# Generated by Django 5.1.15 on 2026-07-04 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0021_formdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('client_label', models.CharField(default='Client', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_program', to='projects.project')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
