# Generated by Django 5.1.15 on 2026-07-04 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('fieldwork', '0008_alter_candidateplot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_referrals_made', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='care.careprogram')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_assignments', to='fieldwork.collectionunit')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_caseload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worker', 'is_active'], name='care_careas_worker__259cf8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='uniq_active_care_assignment_per_unit')],
            },
        ),
    ]
